# Generated by Django 3.2.5 on 2022-05-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalQuestionCategory',
            fields=[
                ('additionalQuestionCategoryID', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('additionalQuestionCategoryOrderNumber', models.IntegerField(blank=True, null=True)),
                ('additionalQuestionCategoryTitle', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answerID', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('answerOrderNumber', models.IntegerField(blank=True, null=True)),
                ('answerTitle', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('questionOrderNumber', models.IntegerField(blank=True, null=True)),
                ('questionTitle', models.CharField(blank=True, max_length=256, null=True)),
                ('answerType', models.CharField(blank=True, choices=[('mcq', 'mcq'), ('text', 'text'), ('bool', 'bool'), ('number', 'number'), ('float', 'float')], max_length=10, null=True)),
                ('userResponse_text', models.CharField(blank=True, max_length=256, null=True)),
                ('userResponse_bool', models.BooleanField(blank=True, null=True)),
                ('userResponse_number', models.IntegerField(blank=True, null=True)),
                ('userResponse_float', models.FloatField(blank=True, null=True)),
                ('answersMCQ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_answerID_set', to='api.answer')),
                ('userResponse_MCQ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_answerID_set', to='api.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionID', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('sectionOrderNumber', models.IntegerField(blank=True, null=True)),
                ('sectionTitle', models.CharField(blank=True, max_length=256, null=True)),
                ('sectionDescription', models.CharField(blank=True, max_length=256, null=True)),
                ('sectionInfo', models.CharField(blank=True, max_length=256, null=True)),
                ('isAnsweredToSection', models.BooleanField(blank=True, null=True)),
                ('isSectionSelectedCurrently', models.BooleanField(blank=True, null=True)),
                ('isExpanded', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('subSectionID', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('subSectionOrderNumber', models.IntegerField(blank=True, null=True)),
                ('subSectionTitle', models.CharField(blank=True, max_length=256, null=True)),
                ('subSectionDescription', models.CharField(blank=True, max_length=256, null=True)),
                ('subSectionInfo', models.CharField(blank=True, max_length=256, null=True)),
                ('isAnsweredToSubSection', models.BooleanField(blank=True, null=True)),
                ('isSubSectionSelectedCurrently', models.BooleanField(blank=True, null=True)),
                ('additionalQuestions', models.ManyToManyField(blank=True, related_name='additional_questionID_set', to='api.Question')),
                ('additionalQuestionsCategories', models.ManyToManyField(blank=True, to='api.AdditionalQuestionCategory')),
                ('commonQuestions', models.ManyToManyField(blank=True, related_name='common_questionID_set', to='api.Question')),
                ('sectionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.section')),
            ],
        ),
        migrations.AddField(
            model_name='additionalquestioncategory',
            name='additionalQuestions',
            field=models.ManyToManyField(blank=True, to='api.Question'),
        ),
    ]
