# Generated by Django 3.2.5 on 2022-05-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='subsection',
            name='SubSectionImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='section',
            name='sectionDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='sectionInfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='subSectionDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='subSectionInfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
